apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sales
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/sergioing1000/k8s-gitops-repo.git
    targetRevision: HEAD
    path: charts/microservice-chart
    helm:
      valueFiles:
        - ../../apps/sales/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
